[bumpversion]
current_version = 0.9.8
commit = True
tag = True

[metadata]
name = bofh
version = attr: bofh.metadata.VERSION
description = Cerebrum bofh client
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/unioslo/pybofh
author = USIT, University of Oslo
author_email = iti-int@usit.uio.no
license = GPL-3.0-or-later
license_file = COPYING
keywords = cerebrum bofh xmlrpc client
classifiers = 
	Development Status :: 4 - Beta
	Environment :: Console
	Intended Audience :: System Administrators
	Programming Language :: Python :: 2.7
	Programming Language :: Python :: 3.6
	Programming Language :: Python :: 3.7
	Programming Language :: Python :: 3.8
	Programming Language :: Python :: 3.9
	Topic :: Software Development :: Libraries
	Topic :: System :: Systems Administration

[options]
include_package_data = True
packages = find:
install_requires = 
	six

[options.packages.find]
include = 
	bofh
	bofh.*

[options.extras_require]
dev = 
	build
	bump2version ~= 1.0
	pytest
	pytest-cov
test = 
	pytest
doc = 
	sphinx
	sphinx-rtd-theme

[options.entry_points]
console_scripts = 
	pybofh = bofh.cli:main

[bdist_wheel]
universal = 1

[bumpversion:file:bofh/metadata.py]

[tool:pytest]
testpaths = tests/
