# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# For a full list of settings, see the documentation:
#
#   <https://www.sphinx-doc.org/en/stable/config>
#
import datetime
import os
import sys


# -- Path setup --------------------------------------------------------------

# Add `bofh` to the sys.path.  This is hacky, but standard for sphinx.
sys.path.insert(0, os.path.abspath('../../'))


# -- Project information -----------------------------------------------------

project = 'bofh'
author = 'University of Oslo'

# Copyright years
_initial_year = 2018
_this_year = datetime.date.today().year

copyright = '{when}, {who}'.format(
    when=('%d - %d' % (_initial_year, _this_year)
          if _this_year > _initial_year
          else str(_initial_year)),
    who=author,
)


def _get_version():
    try:
        import bofh
        return bofh.__version__
    except Exception:
        return ""


# The full version, including alpha/beta/rc tags
release = _get_version()

# The short X.Y version
version = '.'.join(release.split('.')[:2])


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
]

# Add any paths that contain templates here, relative to this directory.
# templates_path = ['_templates']
templates_path = []

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# Ignore specific warnings from sphinx
suppress_warnings = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'collapse_navigation': False,
    'includehidden': False,
    'navigation_depth': 4,
    'prev_next_buttons_location': None,
    'sticky_navigation': True,
    'style_external_links': True,
    'titles_only': True,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']
html_static_path = []

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = '{}-doc'.format(project)


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        '{}.tex'.format(project),
        '{} documentation'.format(project),
        author,
        'manual',
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        'man/pybofh',
        'pybofh',
        'The Cerebrum command line interface',
        [author],
        1,
    ),
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
texinfo_documents = []


# -- Extension configuration -------------------------------------------------

#
# intersphinx - references to other sphinx documentation sites
#
extensions.append("sphinx.ext.intersphinx")
intersphinx_mapping = {
    # Allow referring to the Python standard library
    'python': ("https://docs.python.org/3", None),
}
